#!/usr/bin/env bash
# Installs and configures Nginx on an Ubuntu machine

apt-get update
apt-get -y install nginx

echo "Holberton School for the win!" > /var/www/html/index.html

service nginx restart
