#!/usr/bin/env bash
# Installs and configures Nginx on an Ubuntu machine

set -e

if [ "$(id -u)" -ne 0 ]; then
    SUDO=sudo
else
    SUDO=
fi

$SUDO apt-get update -y
$SUDO apt-get install -y nginx

echo "Holberton School for the win!" | $SUDO tee /var/www/html/index.html > /dev/null

$SUDO service nginx restart

