#!/usr/bin/env bash
# Configures Nginx so that /redirect_me returns a 301 redirect

apt-get update
apt-get -y install nginx

sed -i '/listen \[::\]:80 default_server;/a\
\
	location /redirect_me {\
		return 301 "https://www.youtube.com/watch?v=QH2-TGUlwu4";\
	}' /etc/nginx/sites-enabled/default

echo "Holberton School for the win!" > /var/www/html/index.html

service nginx restart
